### ISSUE TITLE
Ablation studies on the pre-training sigma

### ISSUE THREAD

**Issue by Equationliu** [quanlin-wu/dmae#2]
I guess that the pre-training sigma is set to $\sigma = 0.25$, is there any ablation studies on other values such as `0.5, 1.0, 2.0`?

**Comment by quanlin-wu** [comment]
Yeah, we use sigma=0.25 for all pre-training, and we didn't do ablation studies on it. We only use a low level of Gaussian noise in pre-training because we want to use one pre-trained checkpoint for all fine-tuning tasks.
