### ISSUE TITLE
the link to pretrained checkpoints is not working

### ISSUE THREAD

**Issue by toosi** [quanlin-wu/dmae#4]
Hi!

Thank you for sharing your beautiful work! The links to the pretrained models are not working. 
"This site can’t be reached" is the error.

Thanks,
TT

**Comment by quanlin-wu** [comment]
emmmm. It seems it still works well for me.
![微信截图_20231012232638](https://github.com/quanlin-wu/dmae/assets/106948515/45d5439a-9952-43fb-a02a-9ca7cc872566)

**Comment by toosi** [comment]
Thank you so much for checking. I am based in United States, could it be differences in needed proxies to access the host?

**Comment by quanlin-wu** [comment]
In fact, these files are shared on OneDrive. I think there shouldn't be problems if you are in US.

**Comment by toosi** [comment]
Thanks again. For the record, I checked on different computers on the campus and all gave me the same error, but when I ask my friend in a different university to check, he could send me the checkpoints. Thank you so much for your prompt response. Looking forward to learn more about this work.
