### ISSUE TITLE
cannot download checkpoint, and cannot load pre-trained DMAE model properly

### ISSUE THREAD

**Issue by BruSLiAttack** [quanlin-wu/dmae#5]
I tried running `# download checkpoint if not exist
!wget -nc https://tlgw4g.dm.files.1drv.com/y4meOrodqzrNG2JjHw4cfoF8nZoSvJM9g7hk8G3q58--mBgbWyCvuWP8x91Z6dJxmd4MZBpM4UoX7tNqPr0XYmHKMtXX37ctxAQObsVJ298ldzyY5wS5T3DiliR2T-gSr4XVbG6w76nGSCG6PAws_y6hYLLtaaZlx9QrezOQonTvR2RagiUYt5GyoCkq7JuGyF0T2e7X7HlkfU_47M8gNpCGw`. I got an issue.
![Screenshot from 2024-02-08 16-38-10](https://github.com/quanlin-wu/dmae/assets/118038889/2e1dadf1-d298-455b-8b4f-30b9acc8855d)

Then I downloaded the pre-trained manually and changed the path. It got an error. What should I do to fixed?
![Screenshot from 2024-02-08 16-40-53](https://github.com/quanlin-wu/dmae/assets/118038889/039c9cef-9b0e-4f5e-a778-4d5bbdda3130)

**Comment by quanlin-wu** [comment]
This is because the checkpoint is actually a dictionary of the layers. You can refer to another issue about checkpoint loading.
